### ISSUE TITLE
view manage/heuristics never update heuristic stats data

### ISSUE THREAD

**Issue by adib0u** [CybercentreCanada/assemblyline-ui-frontend#253]
In the manage/heurisitcs view, all the heurstic are in never (Jamais) state.

![manager-heuristics-view](https://user-images.githubusercontent.com/14818085/155090131-458201e7-7fd1-41cf-b4cd-e12bd72e051c.PNG)

It's because the data in this view are the stats data in the database but this data are never update unless you click on each heuristic.

![manager-heuristics-apkaye-10](https://user-images.githubusercontent.com/14818085/155090171-e66fba87-6012-40ee-ac32-522364537c08.PNG)

Is it possible to add a refresh to update stats data on this view ? 
Sorry for the screenshots in french ^^

**Comment by cccs-sgaron** [comment]
Those stats should update nightly and as soon as you select an item. With the amount of signatures that we have it can take an hour or two to update which is why this is a nightly task and would not really be suited for a button.

There should be a statistics container running in your cluster that run the following command: assemblyline_core.metrics.run_statistics_aggregator. Make sure this container is running correctly.
